on: 
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.wizebrains.org
        username: developer@wizebrains.org
        password: developer2024@@
        server-dir: /public_html  # Replace with your server directory path
        local-dir: build
